### ISSUE TITLE
[FEAT] 테스트 환경 구축 및 husky를 통한 테스트 자동화, Schedule 테스트 코드 작성

### ISSUE THREAD

**Issue by HYOSITIVE** [Team-DragMe/DragMe-Server#132]
**Feature Request**
기능 설명 : 테스트 환경을 구축하고 husky를 통해 테스트를 자동화합니다.

**To-Do List**
- [x] 테스트를 위한 라이브러리 설치 (jest, supertest, babel, cross-env)
- [x] husky 설치
- [x] 계획블록 삭제 API 로직 수정
- [x] Schedule 라우트 테스트 코드 작성
- [x] husky test script 추가
