### ISSUE TITLE
[FEAT] Eslint, Prettier 설정

### ISSUE THREAD

**Issue by HYOSITIVE** [Team-DragMe/DragMe-Server#3]
**Feature Request**
기능 설명 : Eslint, Prettier를 설정합니다.

**To-Do List**
- [x] Eslint, Prettier 패키지 설치
- [x] Eslint 설정 파일 작성
- [x] Prettier 설정 파일 작성
- [x] 충돌 방지 옵션 설정 (Eslint-Prettier Config)
