### ISSUE TITLE
[FEAT] User 콜렉션 생성

### ISSUE THREAD

**Issue by HYOSITIVE** [Team-DragMe/DragMe-Server#5]
**Feature Request**
기능 설명 : User 콜렉션을 생성합니다.

**To-Do List**
- [x] mongoose 패키지 설치
- [x] User model 정의
- [x] User interface 정의
