### ISSUE TITLE
[IMPROVE] 정보 작성 API 점검 및 보완

### ISSUE THREAD

**Issue by HYOSITIVE** [Team-DragMe/DragMe-Server#84]
**About API**
API 설명 : 정보 작성 API를 점검 및 보완합니다.

**To-Do List**

- [x] id 길이 체크하는 로직 확인 후 삭제
- [x] Controller에 Slack Error Monitoring 코드 추가
- [x] request query, body 점검 (id처럼 자원 식별용이면 query)
- [x] scheduleId도 type string으로 통일
- [x] userId는 무조건 Controller단에서 string으로 만들고 넘기기
- [x] req.body로 받은 데이터 dto 적용되어 있는지 확인
- [x] 더 효율적으로 할 수 있을 것 같은 부분 있으면 알려주기
- [x] API 명세서 재확인 후 수정
